### ISSUE TITLE
Get Prediction

### ISSUE THREAD

**Issue by alikhodadoost** [anastasios-stamoulis/deep-learning-with-csharp-and-cntk#10]
Hi, I'm Trying to get prediction of the model I have. for example in ch2 first look at a neural network.
but there is no function I can find to do so using cntk.Can you help me with that?

**Comment by anastasios-stamoulis** [comment]
I know the pain... When I started with Deep Learning, I was very surprised to see that most people are so caught up with training/evaluating networks, that it was very difficult to find a simple tutorial that explains the 3--4 lines of code required to get a prediction from a trained model. 

With CNTK/C#, to get the prediction of a trained model you'll use the methods Evaluate and GetDenseData. First, you supply the inputs of the model to the Evaluate method, and then you get them from the corresponding output variable using the method GetDenseData. You can take a look at the [Neural Transfer](https://github.com/anastasios-stamoulis/deep-learning-with-csharp-and-cntk/tree/master/DeepLearning/Ch_08_Neural_Style_Transfer) and [Variational AutoEncoders](https://github.com/anastasios-stamoulis/deep-learning-with-csharp-and-cntk/tree/master/DeepLearning/Ch_08_Generating_Images_With_VAEs) projects to see this in action.
