### ISSUE TITLE
LSTM Example with non binary data

### ISSUE THREAD

**Issue by anirudh264** [anastasios-stamoulis/deep-learning-with-csharp-and-cntk#3]
How would you implement the LSTM example with non binary data. I was wondering if you could provide a quick explanation or example?

**Comment by anastasios-stamoulis** [comment]
Please take a look at Ch_08_Text_Generation_With_LSTM, that I just added. You could start by looking at the method run_cntk() in ch8-1.py, which shows how the Keras example is ported in CNTK+Python.
