### ISSUE TITLE
Unfound Directories

### ISSUE THREAD

**Issue by YanYas** [anastasios-stamoulis/deep-learning-with-csharp-and-cntk#4]
Great work, really helpful!

I caught one error in the with Using Pre-trained _Convnet Models - "'Cannot open file 'D:\kaggle_cats_dogs\cat.582.jpg"

The same error is thrown with "...Convnets with Small Datasets"

**Comment by anastasios-stamoulis** [comment]
No worries. Just follow the directions in the [README.md](https://github.com/anastasios-stamoulis/deep-learning-with-csharp-and-cntk/blob/master/DeepLearning/Ch_05_Using_Convnets_With_Small_Datasets/README.md) , and download the dataset.

**Comment by YanYas** [comment]
Quick update/suggestion, cats_dogs data is also available [here](https://www.microsoft.com/en-us/download/details.aspx?id=54765)
