### ISSUE TITLE
Directory Not found with Word Embedding

### ISSUE THREAD

**Issue by YanYas** [anastasios-stamoulis/deep-learning-with-csharp-and-cntk#5]
Try to run this but found this little problem:
```
"Error with "Ch_06_Using_Word_Embeddings"

System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\Users\anastasios\Downloads\aclImdb\train\neg'.'"
```

**Comment by anastasios-stamoulis** [comment]
You'll need to download the dataset. Just follow "Step 1: Download the Glove embeddings and create the embeddings matrix" in the [README.md](https://github.com/anastasios-stamoulis/deep-learning-with-csharp-and-cntk/blob/master/DeepLearning/Ch_06_Using_Word_Embeddings/README.md)
