### ISSUE TITLE
DLL 'Cntk.Core.CSBinding-2.3.1.dll'

### ISSUE THREAD

**Issue by superdrin** [anastasios-stamoulis/deep-learning-with-csharp-and-cntk#8]
I get this error 
DllNotFoundException: Unable to load DLL 'Cntk.Core.CSBinding-2.3.1.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Can you help?
Thanks,
Stefano
PS: Windows 10
     Visual Studio Comunity 2017

**Comment by anastasios-stamoulis** [comment]
Do you still get this error?  I just got a fresh copy from GitHub, and tried it out with Visual Studio 2017 (Community), and things work fine.

**Comment by superdrin** [comment]
Thanks Anastasios but I already solved.
You did an excellent work ! Congratulation.
Keep it up.
Have a great day!
Stefano Campanella


------ Original Message ------

**Comment by superdrin** [comment]
Hello !
I use Visual Studio Community 2017.
With your fresh copy I still get these error:
-in Ch_05_Class_Activation_Heatmaps
-in Ch_05_Visualizing_Convnet_Filters
Severity	Code	Description	Project	File	Line	Suppression State	
Error	C1189	#error: Currently CNTK only supports X64 platform and Visual 
Studio 2015 Update 3. Please configure your project to use x64 platform 
and build your project with Visual Studio 
2015.	CPPUtil	d:\csharp\deep-learning-with-csharp-and-cntk-master\deeplearning\packages\cntk.gpu.2.3.1\build\non-supported\include\cntklibrary.h	8
- in Ch_06_Sequence_Processing_With_Convnets
System.ApplicationException
   HResult=0x80131600
   Message=Inside File: Matrix.cpp  Line: 1829  Function: 
Microsoft::MSR::CNTK::Matrix<float>::AdamUpdate  -> Feature Not 
Implemented.

[CALL STACK]
     > Microsoft::MSR::CNTK::Matrix<float>::  AdamUpdate
     - CNTK::Internal::  ZeroesWithDynamicAxesLike (x2)
     - CNTK::  UniversalLearner
     - CNTK::TrainingParameterSchedule<unsigned __int64>::  Transform
     - CNTK::Trainer::  TotalNumberOfUnitsSeen
     - CNTK::Trainer::  TrainMinibatch (x2)
     - CSharp_CNTK_Trainer__TrainMinibatch__SWIG_2
     - 00007FFDE0CDED35 (SymFromAddr() error: The specified module could 
not be found.)


   Source=Cntk.Core.Managed-2.3.1
   StackTrace:
    at CNTK.Trainer._TrainMinibatch(UnorderedMapVariableValuePtr 
arguments, Boolean isSweepEndInArguments, DeviceDescriptor 
computeDevice)
    at DeepLearningWithCNTK.TrainingEngine.training_phase() in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Util.cs:line 
1137
    at DeepLearningWithCNTK.TrainingEngine.train(Double threshold) in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Util.cs:line 
1070
    at Ch_06_Sequence_Processing_With_Convnets.Program.run() in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Ch_06_Sequence_Processing_With_Convnets\Program.cs:line 
48
    at Ch_06_Sequence_Processing_With_Convnets.Program.Main(String[] 
args) in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Ch_06_Sequence_Processing_With_Convnets\Program.cs:line 
12

-in Ch_06_Using_Word_Embeddings
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 
'C:\Users\anastasios\Downloads\aclImdb\train\neg'.'
-in Ch_08_Deep_Dream
System.NotSupportedException: 'Please set PYTHON_HOME_ properly'
-in Ch_08_Text_Generation_With_LSTM
System.ApplicationException: 'Inside File: Matrix.cpp Line: 1829 
Function: Microsoft::MSR::CNTK::Matrix<float>::AdamUpdate -> Feature Not 
Implemented.
System.ApplicationException
   HResult=0x80131600
   Message=Inside File: Matrix.cpp  Line: 1829  Function: 
Microsoft::MSR::CNTK::Matrix<float>::AdamUpdate  -> Feature Not 
Implemented.

[CALL STACK]
     > Microsoft::MSR::CNTK::Matrix<float>::  AdamUpdate
     - CNTK::Internal::  ZeroesWithDynamicAxesLike (x2)
     - CNTK::  UniversalLearner
     - CNTK::TrainingParameterSchedule<unsigned __int64>::  Transform
     - CNTK::Trainer::  TotalNumberOfUnitsSeen
     - CNTK::Trainer::  TrainMinibatch (x2)
     - CSharp_CNTK_Trainer__TrainMinibatch__SWIG_2
     - 00007FFDE0CFCDB5 (SymFromAddr() error: The specified module could 
not be found.)


   Source=Cntk.Core.Managed-2.3.1
   StackTrace:
    at CNTK.Trainer._TrainMinibatch(UnorderedMapVariableValuePtr 
arguments, Boolean isSweepEndInArguments, DeviceDescriptor 
computeDevice)
    at DeepLearningWithCNTK.TrainingEngine.training_phase() in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Util.cs:line 
1137
    at DeepLearningWithCNTK.TrainingEngine.train(Double threshold) in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Util.cs:line 
1070
    at Ch_08_Text_Generation_With_LSTM.Program.run() in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Ch_08_Text_Generation_With_LSTM\Program.cs:line 
162
    at Ch_08_Text_Generation_With_LSTM.Program.Main(String[] args) in 
D:\CSharp\deep-learning-with-csharp-and-cntk-master\DeepLearning\Ch_08_Text_Generation_With_LSTM\Program.cs:line 
12

Have a great day!
Stefano


------ Original Message ------
