### ISSUE TITLE
layers with CNTK 2.3.1 and 2.6

### ISSUE THREAD

**Issue by YanYas** [anastasios-stamoulis/deep-learning-with-csharp-and-cntk#9]

**Comment by YanYas** [comment]
My apologies, I had this as a draft for a while and sent it by accident. The examples I have tested so far all work with CNTK 2.6. Closing.

**Comment by anastasios-stamoulis** [comment]
No problem. I also would like to upgrade everything to the latest CNTK release, but I am just waiting for someone from Microsoft to close [3376](https://github.com/Microsoft/CNTK/pull/3376). When this is done, there will be no need for C++ and P/Invoke, and the whole repository will just be Python and C#.

**Comment by YanYas** [comment]
They're really good examples so I hope it works out. Thanks once again.
